### ISSUE TITLE
hello pr-nizar

### ISSUE THREAD

**Issue by chonghua** [pr-nizar/securelog#1]
hello pr-nizar，
I am sorry to give you a message here because I can't find your contact information. Your blogger theme is very beautiful, I like it very much, I would like to ask you if you are willing to share your theme of the XML file.

**Comment by pr-nizar** [comment]
Hi @chonghua!
I'll be posting the XML file for my theme on a repo here soon (maybe today or tomorrow).. Stay tuned!
